[workspace]
git_release_body = """
{{ changelog }}

{% if remote.contributors %}
### 🤝 Contributors
A huge thank you to everyone who contributed to this release:
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[changelog]
commit_parsers = [
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
  { message = "^test", skip = true },
  { message = "^style", skip = true },
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^refactor", group = "Refactored" },
  { message = "^docs", group = "Documentation" },
  { message = ".*", group = "Other" },
]
