use std::{
    fs,
    path::{Path, PathBuf},
};

use clap::Parser;

#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum, Default)]
pub(crate) enum Format {
    Silent,
    Brief,
    #[default]
    Long,
}

#[derive(Debug, Parser)]
#[command(rename_all = "kebab_case")]
#[command(about, author, version)]
pub(crate) struct Args {
    #[arg(long, help = "Install mamoru automatically into .git/hooks/")]
    pub(crate) init: bool,

    #[arg(
        short,
        long,
        requires = "init",
        help = "Overwrite existing hook during init"
    )]
    pub(crate) force: bool,

    #[arg(long, help = "Only use ASCII characters for output")]
    pub(crate) ascii_only: bool,

    #[arg(index = 1, default_value = ".git/COMMIT_EDITMSG")]
    pub(crate) path: PathBuf,

    #[arg(long, ignore_case = true, value_enum, default_value_t = Format::Long)]
    pub(crate) format: Format,
}

pub fn initialization(args: &Args) -> Result<(), Box<dyn std::error::Error>> {
    let dir = Path::new(".git").join("hooks");

    let path = dir.join("commit-msg");

    if !dir.exists() {
        fs::create_dir_all(&dir)?;
    }

    if path.exists() && !args.force {
        return Err(format!(
            "A hook already exists at `{}`. Use `--force` to overwrite it.",
            path.display()
        )
        .into());
    }

    let exe = std::env::current_exe()?;
    let exe_path_str = exe.to_string_lossy();

    let script = format!(
        "#!/bin/sh\n# Generated by mamoru\n\"{}\" \"$@\"\n",
        exe_path_str
    );

    fs::write(&path, script)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&path, perms)?;
    }

    println!("Mamoru installed successfully!");
    Ok(())
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn verify_app() {
        use clap::CommandFactory;
        Args::command().debug_assert();
    }
}
